name: Release builds

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build-windows:
    name: Build Windows installer
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and publish (electron-builder)
        run: npx electron-builder --win nsis --x64 --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'

      - name: Upload build artifacts (optional)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: dist/**
